package server

import (
	"bytes"
	"crypto"
	"crypto/ecdsa"
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"net/url"
	"os"
	"strings"
)

// ResourceClient describes one machine-to-machine OAuth client that is
// pre-provisioned to authenticate with RFC 7523 private_key_jwt, typically a
// resource server performing token exchange. Unlike ConnectorConfig, the key
// material here is a public key and is not sensitive.
type ResourceClient struct {
	ClientID string `json:"client_id"`
	Name     string `json:"name"`
	Resource string `json:"resource"`
	// Exactly one of PublicKeyPEM or PublicKeyFile must be set. PublicKeyFile
	// is convenient when the key is generated by a separate provisioning step
	// (a secrets manager, an init container) and avoids awkward JSON-escaping
	// of multi-line PEM text in hand-authored config.
	PublicKeyPEM  string `json:"public_key_pem"`
	PublicKeyFile string `json:"public_key_file"`
	// Algorithm is the JWS algorithm this client signs its client_assertion
	// with: "RS256" (default), "PS256", or "ES256". It must be compatible
	// with the key's own type (RS256/PS256 need an RSA key, ES256 needs a
	// P-256 EC key) — checked at load time, not at first use.
	Algorithm string `json:"algorithm"`
}

// LoadResourceClients reads a JSON array of pre-provisioned private_key_jwt
// clients from disk. Each entry's resource URL and public key are validated
// so malformed configuration fails fast at startup.
func LoadResourceClients(path string) ([]ResourceClient, error) {
	if path == "" {
		return nil, nil
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read resource clients file: %w", err)
	}
	var clients []ResourceClient
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&clients); err != nil {
		return nil, fmt.Errorf("parse resource clients file: %w", err)
	}
	seen := make(map[string]bool, len(clients))
	for i, client := range clients {
		if client.ClientID == "" {
			return nil, errors.New("resource client is missing client_id")
		}
		resource, err := url.Parse(client.Resource)
		if err != nil || resource.Scheme == "" || resource.Host == "" || resource.Fragment != "" {
			return nil, fmt.Errorf("resource client %q must bind an absolute resource URL", client.ClientID)
		}
		if seen[client.ClientID] {
			return nil, fmt.Errorf("resource client %q is duplicated", client.ClientID)
		}
		seen[client.ClientID] = true
		if (client.PublicKeyPEM == "") == (client.PublicKeyFile == "") {
			return nil, fmt.Errorf("resource client %q must set exactly one of public_key_pem or public_key_file", client.ClientID)
		}
		if client.PublicKeyFile != "" {
			keyData, err := os.ReadFile(client.PublicKeyFile)
			if err != nil {
				return nil, fmt.Errorf("resource client %q: read public_key_file: %w", client.ClientID, err)
			}
			client.PublicKeyPEM = string(keyData)
			clients[i].PublicKeyPEM = client.PublicKeyPEM
		}
		if client.Algorithm == "" {
			client.Algorithm = "RS256"
			clients[i].Algorithm = client.Algorithm
		}
		if !validAlgorithm(client.Algorithm) {
			return nil, fmt.Errorf("resource client %q has an unsupported algorithm %q", client.ClientID, client.Algorithm)
		}
		key, err := parsePublicKeyPEM(client.PublicKeyPEM)
		if err != nil {
			return nil, fmt.Errorf("resource client %q has an invalid public key: %w", client.ClientID, err)
		}
		if !keyMatchesAlgorithm(client.Algorithm, key) {
			return nil, fmt.Errorf("resource client %q: public key type does not match algorithm %q", client.ClientID, client.Algorithm)
		}
	}
	return clients, nil
}

// parsePublicKeyPEM parses a PKIX PEM-encoded public key and returns it as
// either *rsa.PublicKey or *ecdsa.PublicKey.
func parsePublicKeyPEM(value string) (crypto.PublicKey, error) {
	block, _ := pem.Decode([]byte(value))
	if block == nil {
		return nil, errors.New("public key is not PEM encoded")
	}
	parsed, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse public key: %w", err)
	}
	switch parsed.(type) {
	case *rsa.PublicKey, *ecdsa.PublicKey:
		return parsed, nil
	default:
		return nil, errors.New("public key must be RSA or EC")
	}
}

// verifyClientAssertion validates an RFC 7523 private_key_jwt client
// assertion against a registered client's public key and returns its claims.
// The assertion's alg header must match algorithm exactly — the client
// authenticates with whichever single algorithm it registered a key for, not
// any algorithm this server happens to support. The caller is responsible
// for replay protection (jti) and for checking that the client is actually
// registered for private_key_jwt.
func verifyClientAssertion(assertion, publicKeyPEM, algorithm, clientID, audience string) (map[string]any, error) {
	key, err := parsePublicKeyPEM(publicKeyPEM)
	if err != nil {
		return nil, err
	}
	parts := strings.Split(assertion, ".")
	if len(parts) != 3 {
		return nil, errors.New("client assertion is malformed")
	}
	var header struct {
		Algorithm string `json:"alg"`
	}
	if err := decodeJWTPart(parts[0], &header); err != nil || header.Algorithm != algorithm {
		return nil, errors.New("client assertion algorithm does not match the registered algorithm")
	}
	var claims map[string]any
	if err := decodeJWTPart(parts[1], &claims); err != nil {
		return nil, errors.New("client assertion claims are invalid")
	}
	signature, err := base64.RawURLEncoding.DecodeString(parts[2])
	if err != nil {
		return nil, errors.New("client assertion signature is malformed")
	}
	if verifySignature(algorithm, key, []byte(parts[0]+"."+parts[1]), signature) != nil {
		return nil, errors.New("client assertion signature is invalid")
	}
	if claims["iss"] != clientID || claims["sub"] != clientID {
		return nil, errors.New("client assertion issuer/subject must match the client_id")
	}
	if !audienceContains(claims["aud"], audience) {
		return nil, errors.New("client assertion audience is invalid")
	}
	if !validExpiry(claims["exp"]) {
		return nil, errors.New("client assertion is expired")
	}
	jti, ok := claims["jti"].(string)
	if !ok || jti == "" {
		return nil, errors.New("client assertion is missing jti")
	}
	return claims, nil
}
